    

FROM python:3.8-slim
WORKDIR /app
COPY . .
RUN pip install --trusted-host pypi.python.org -r /app/requirements.txt
EXPOSE 80
CMD ["python", "-m", "src.app.start_fastapi"]
# CMD ["./refs/deploy_tools/serve-api.sh"]

# RUN pip install -r /app/requirements.txt
# EXPOSE 5000
# CMD ["python", "-m", "src.app.start-flask"]



