    

FROM python:3.8-slim
WORKDIR /app
RUN pip install --trusted-host pypi.python.org -r /app/requirements.txt
COPY . .

ARG ENV_TYPE
ARG SERVER_TYPE
ENV ENV_TYPE ${ENV_TYPE}
ENV SERVER_TYPE ${SERVER_TYPE}

EXPOSE 80
CMD ["python", "-m", "src.app.start"]



