    

FROM python:3.8-slim
WORKDIR /app
COPY . .
RUN pip install --trusted-host pypi.python.org -r /app/requirements.txt
EXPOSE 80
CMD ["python", "./app-fastapi.py"]

# RUN pip install -r /app/requirements.txt
# EXPOSE 5000
# CMD ["./refs/deploy_tools/serve-api.sh"]


