name: Build Dev

on: 
  push:
    branches: 
      - dev
      - qas

env:
  ACR_USER : DatalakeEpicContainerRegistry
  DKR_IMAGE: data-functions-wap-dev
  DKR_TAG  : '1.0.23'
   
    
jobs :
  init :
    runs-on : ubuntu-latest
    outputs : 
      env-branch : ${{steps.set-variables.outputs.env-branch}}
      registry   : ${{steps.set-variables.outputs.registry}}
      app-name   : ${{steps.set-variables.outputs.app-name}}

    steps : 
      - name : Set Variables
        id   : set-variables
        run  : |
          case ${GITHUB_BASE_REF##*/} in
            "dev") 
              echo "::set-output name=env-branch::dev"
              echo "::set-output name=registry::datalakeepiccontainerregistry.azurecr.io"
              echo "::set-output name=app-name::wap-validation-services-dev"
              ;;
            "qas")
              echo "::set-output name=env-branch::qas"
              echo "::set-output name=registry::acrCrossChannelDataQas.azurecr.io"
              echo "::set-output app-name::as-validationServices-data-qas"
              ;;
            "stg")
              echo "::set-output name=env-branch::stg"
              echo "::set-output name=registry::acrCrossChannelDataStg.azurecr.io"
              echo "::set-output name=app-name::as-validationServices-data-stg"
              ;;
          esac 
  
  build-and-deploy-dev :
    runs-on     : ubuntu-latest
    needs       : init
    environment : ${{needs.init.outputs.env-brach}} 
    
    steps :
    - name : Checkout GitHub Actions
      uses : actions/checkout@main
      with :
        ref : ${{needs.init.outputs.env-branch}}
     
    - name : Build and push to registry 
      id   : container-registry
      uses : mr-smithers-excellent/docker-build-push@v5.5
      with : 
        dockerfile : dockerfile.ci
        image      : ${{env.DKR_IMAGE}}
        tags       : ${{env.DKR_TAG}}
        registry   : ${{needs.init.outputs.registry}}
        username   : ${{env.ACR_USER}}
        password   : ${{secrets.ACR_PASS}}
        
        
    - name : Deploy to App Service
      uses : azure/webapps-deploy@v2
      with :
        app-name       : ${{needs.init.outputs.app-name}}
        images         : ${{needs.init.outputs.registry}}/${{env.DKR_IMAGE}}:${{env.DKR_TAG}}
        publish-profile: ${{secrets.WAP_PUBLISH}}
       