name: Build Dev

on: 
  push:
    branches: 
      - dev

env:
  WAP_SERV : wap-validation-services-dev
  ACR_HOST : datalakeepiccontainerregistry.azurecr.io
  ACR_USER : DatalakeEpicContainerRegistry
  DKR_IMAGE: data-functions-wap-dev
  DKR_TAG  : "1.0.10"
   
    
jobs:
  build-and-deploy-dev:
    environment: dev
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout GitHub Actions
      uses: actions/checkout@main
      with:
        ref: 'dev'
     
    - name: Build and push container image to registry 
      id: container-registry
      uses: mr-smithers-excellent/docker-build-push@v5.5
      with: 
        dockerfile: dockerfile.ci
        image     : ${{ env.DKR_IMAGE }}
        registry  : ${{ env.ACR_HOST }}
        tags      : ${{ env.DKR_TAG }}
        username  : ${{ env.ACR_USER }}
        password  : ${{ secrets.ACR_PASS }}
        
        
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name       : ${{env.WAP_SERV}}
        images         : ${{env.ACR_HOST}}/${{env.DKR_IMAGE}}:${{env.DKR_TAG}}
        publish-profile: ${{secrets.WAP_PUBLISH}}
        