name : Build and Deploy 

on : 
  push :
    branches : ['dev', 'qas', 'stg', 'prd', 'drp']
  pull_request : 
    branches : ['dev', 'qas', 'stg', 'prd', 'drp']

env :
  GH_REPO    : Bineo2/data-functions
  BRANCH_ENV : ${{github.base_ref || github.ref_name}}
  DKR_IMAGE  : data-functions-wap
  DKR_TAG    : '1.0.33'


jobs :
  build-and-deploy :
    runs-on     : ubuntu-latest
    environment : ${{github.base_ref || github.ref_name}}     
    steps : 

    - name : Set Variables
      id   : set-variables
      run  : |
        case "${{env.BRANCH_ENV}}" in
          "dev") 
            echo "WAP_NAME=wap-validation-services-dev"    >> $GITHUB_ENV;;
          "qas")
            echo "WAP_NAME=as-validationServices-data-qas" >> $GITHUB_ENV;;
          "stg")
            echo "WAP_NAME=as-validationServices-adm-stg"  >> $GITHUB_ENV;;
          "prd")
            echo "WAP_NAME=as-validationServices-data-prd" >> $GITHUB_ENV;;
          "drp")
            echo "WAP_NAME=as-validationServices-data-drp" >> $GITHUB_ENV;;
        esac

    - name : Checkout GitHub Actions
      uses : actions/checkout@main
      with :
        repository : ${{env.GH_REPO}}
        ref        : ${{env.BRANCH_ENV}}
     
    - name : Build and push to registry 
      id   : container-registry
      uses : mr-smithers-excellent/docker-build-push@v5.5
      with : 
        registry   : ${{secrets.ACR_USERNAME}}.azurecr.io
        username   : ${{secrets.ACR_USERNAME}}
        password   : ${{secrets.ACR_PASSWORD}}
        dockerfile : dockerfile.ci
        image      : ${{env.DKR_IMAGE}}
        tags       : ${{env.DKR_TAG}}-${{env.BRANCH_ENV}}
        buildArgs  : ENV_TYPE=${{env.BRANCH_ENV}},SERVER_TYPE=wap
        
    - name : Deploy to App Service
      uses : azure/webapps-deploy@v2
      with :
        images  : '${{secrets.ACR_USERNAME}}.azurecr.io/${{env.DKR_IMAGE}}:${{env.DKR_TAG}}-${{env.BRANCH_ENV}}'
        app-name : ${{env.WAP_NAME}}
        publish-profile : ${{secrets.WAP_PUBLISH}}
       