name: Build QAs

on: 
  push:
    branches: 
      - qas

env:
  WAP_SERV : as-validationServices-data-qas
  DKR_IMAGE: data-functions-wap-qas
  DKR_TAG  : "1.0.22"
   
    
jobs:
  build-and-deploy-qas:
    environment: qas
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout GitHub Actions
      uses: actions/checkout@main
      with:
        ref: 'qas'
     
    - name: Build and push container image to registry 
      id: container-registry
      uses: mr-smithers-excellent/docker-build-push@v5.5
      with: 
        dockerfile: dockerfile.ci
        image     : ${{ env.DKR_IMAGE }}
        tags      : ${{ env.DKR_TAG }}
        registry  : ${{ secrets.ACR_HOST }}
        username  : ${{ secrets.ACR_USERNAME }}
        password  : ${{ secrets.ACR_PASSWORD }}
        
        
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name       : ${{secrets.WAP_SERV}}
        images         : ${{secrets.ACR_HOST}}/${{env.DKR_IMAGE}}:${{env.DKR_TAG}}
        publish-profile: ${{secrets.WAP_PUBLISH}}
        
