name : Build and Deploy 

on: 
  workflow_dispatch:
    inputs:
      deploy_to :
        description : 'Environment to deploy to'
        required : true
        default : 'dev'

env :
  GH_REPO : Bineo2/data-functions
  DKR_IMAGE : data-functions-wap
  DKR_TAG : '1.0.50'

jobs :
  build-and-deploy :
    runs-on : ubuntu-latest
    environment : ${{github.event.inputs.deploy_to}}
    steps : 
    - name : Set Variables
      id : set-variables
      run : |
        case "${{github.event.inputs.deploy_to}}" in
          "dev") 
            echo "WAP_NAME=wap-validation-services-dev"    >> $GITHUB_ENV;;
          "qas")
            echo "WAP_NAME=as-validationServices-data-qas" >> $GITHUB_ENV;;
          "stg")
            echo "WAP_NAME=as-validationServices-adm-stg"  >> $GITHUB_ENV;;
          "stg2")
            echo "WAP_NAME=as-validationServices-adm-stg"  >> $GITHUB_ENV;;
          "prd")
            echo "WAP_NAME=as-validationServices-data-prd" >> $GITHUB_ENV;;
          "prd2")
            echo "WAP_NAME=as-validationServices-data-prd" >> $GITHUB_ENV;;
          "drp")
            echo "WAP_NAME=as-validationServices-data-drp" >> $GITHUB_ENV;;
        esac

    - name : Checkout GitHub Actions
      uses : actions/checkout@main
     
    - name : Build and push to registry 
      id   : container-registry
      uses : mr-smithers-excellent/docker-build-push@v5.5
      with : 
        dockerfile : dockerfile.ci
        registry   : ${{secrets.ACR_HOST}}
        username   : ${{secrets.ACR_USERNAME}}
        password   : ${{secrets.ACR_PASSWORD}}
        image      : ${{env.DKR_IMAGE}}
        tags       : ${{env.DKR_TAG}}-${{github.event.inputs.deploy_to}}
        buildArgs  : SERVER_TYPE=wap,ENV_TYPE=${{github.event.inputs.deploy_to}}
        
    - name : Deploy to App Service
      uses : azure/webapps-deploy@v2
      with :
        images : '${{secrets.ACR_HOST}}/${{env.DKR_IMAGE}}:${{env.DKR_TAG}}-${{github.event.inputs.deploy_to}}'
        app-name : ${{env.WAP_NAME}}
        slot-name : ${{secrets.WAP_SLOT}}
        publish-profile : ${{secrets.WAP_PUBLISH}}
       