name : Build and Deploy 

on: 
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'

env :
  GH_REPO   : Bineo2/data-functions
  DEPLOY_ENV: ${{github.event.inputs.deploy_env}}
  DKR_IMAGE : data-functions-wap
  DKR_TAG   : '1.0.40'

jobs :
  build-and-deploy :
    runs-on     : ubuntu-latest
    environment : ${{github.event.inputs.deploy_env}}
    steps : 
    - name : Set Variables
      id   : set-variables
      run  : |
        case "${{env.DEPLOY_ENV}}" in
          "dev") 
            echo "WAP_NAME=wap-validation-services-dev"    >> $GITHUB_ENV;;
          "qas")
            echo "WAP_NAME=as-validationServices-data-qas" >> $GITHUB_ENV;;
          "stg")
            echo "WAP_NAME=as-validationServices-adm-stg"  >> $GITHUB_ENV;;
          "prd")
            echo "WAP_NAME=as-validationServices-data-prd" >> $GITHUB_ENV;;
          "drp")
            echo "WAP_NAME=as-validationServices-data-drp" >> $GITHUB_ENV;;
        esac

    - name : Checkout GitHub Actions
      uses : actions/checkout@main
      with :
        repository : ${{env.GH_REPO}}
        ref        : ${{env.DEPLOY_ENV}}
     
    - name : Build and push to registry 
      id   : container-registry
      uses : mr-smithers-excellent/docker-build-push@v5.5
      with : 
        registry   : ${{secrets.ACR_HOST}}
        username   : ${{secrets.ACR_USERNAME}}
        password   : ${{secrets.ACR_PASSWORD}}
        dockerfile : dockerfile.ci
        image      : ${{env.DKR_IMAGE}}
        tags       : ${{env.DKR_TAG}}-${{env.DEPLOY_ENV}}
        buildArgs  : ENV_TYPE=${{env.DEPLOY_ENV}},SERVER_TYPE=wap
        
    - name : Deploy to App Service
      uses : azure/webapps-deploy@v2
      with :
        images  : '${{secrets.ACR_HOST}}/${{env.DKR_IMAGE}}:${{env.DKR_TAG}}-${{env.DEPLOY_ENV}}'
        app-name : ${{env.WAP_NAME}}
        publish-profile : ${{secrets.WAP_PUBLISH}}
       