name: Functions for Backbase, RFC. 

on: 
  push:
    branches: 
      - dev

env:
  DKR_IMAGE: data-get-rfc-webapp-dev
  DKR_TAG: "1.0.1"
  WAP_SERV: wap-validation-services-dev
  ACR_HOST: "datalakeepiccontainerregistry.azurecr.io"
      
jobs:
  build-and-deploy-dev:
    environment: dev
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout GitHub Actions
      uses: actions/checkout@main
      with:
        ref: 'dev'
     
    - name: Build and push container image to registry 
      id: container-registry
      uses: mr-smithers-excellent/docker-build-push@v5.5
      with: 
        dockerfile: dockerfile.ci
        image     : ${{ env.DKR_IMAGE }}
        registry  : ${{ env.ACR_HOST }}
        tags      : ${{ env.DKR_TAG }}
        username  : ${{ secrets.ACR_USER }}
        password  : ${{ secrets.ACR_PASS }}
        
        
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name       : ${{env.WAP_SERV}}
        images         : ${{env.ACR_HOST}}/${{env.DKR_IMAGE}}:${{env.DKR_TAG}}
        publish-profile: ${{secrets.WAP_PUBLISH}}
        